### PR TITLE
Fix Debian bug

### PR DESCRIPTION
**Pull request by archetipico**
Trying to fix a bug in Debian

### CODE REVIEW

**Comment by MasterCruelty** [comment]
what is the bug you're trying to fix @archetipico

**Review by MasterCruelty — COMMENTED** [review]
I don't understand what kind of configuration you're meanig to do in these lines of code

**Comment by archetipico** [comment]
The problem arises when packages are wrongly installed

`--configure -a` is the configuration process of such packages
`--fix-broken install` fixes broken dependencies

**Review by MasterCruelty — APPROVED** [review]
ok

**Pull request merged**
